name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: sample test case 10
      id: sample-test-case-10
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: sample test case 10
        setup-command: ''
        command: java org.junit.runner.JUnitCore TestMain
        input: 5 5
        expected-output: '10'
        comparison-method: exact
        timeout: 10
        max-score: 6
    - name: Sample Test cse 20
      id: sample-test-cse-20
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Sample Test cse 20
        setup-command: ''
        command: java org.junit.runner.JUnitCore TestMain
        input: 10 10
        expected-output: '20'
        comparison-method: exact
        timeout: 10
        max-score: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        SAMPLE-TEST-CASE-10_RESULTS: "${{steps.sample-test-case-10.outputs.result}}"
        SAMPLE-TEST-CSE-20_RESULTS: "${{steps.sample-test-cse-20.outputs.result}}"
      with:
        runners: sample-test-case-10,sample-test-cse-20
